### ISSUE TITLE
New Chapter for Cairo, Egypt

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#120]
__Summary__
Maptime name: __MaptimeCairo__
Contact name: Ahmed Osman
Date submitted: 2015-07-05 08:44:29

- [ ] Add GH admins to new team: ahmednosman
- [ ] Add Location (Cairo, Egypt) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
Woot!
![darksideofthemoon](https://cloud.githubusercontent.com/assets/1212178/8527009/0a741642-23bf-11e5-90ac-208f6a399b56.png)

**Comment by geobrando** [comment]
Hello @ahmednosman. I created a repo to manage your web page, which uses our starter template. I gave you write privileges.  

repo: https://github.com/maptime/cairo
site: http://maptime.io/cairo

I edited the  [_config.yml](https://github.com/maptime/cairo/blob/gh-pages/_config.yml) file in the repo for you.  We recommend securing a twitter handle and using it to promote your events and interact with your community. (e.g. `@MaptimeCairo`).  If you choose to create a twitter account, please update the _config.yml file or let me know so that I can edit it for you.

Let me know if you need help learning how to create posts/events on your site.  You're also free to scrap this starter template if you prefer to build a custom web page.

We'll also need to get you added to the map and list at http://maptime.io/chapters.  To do that, we will add your chapter to [chapters.json](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json?short_path=672e323).  If you feel comfortable doing so, please edit the file with your chapter information using the existing entries as an example and submit a pull request.  If not, we can take care of that for you.  Just respond to this issue.

You should have received an invite to join our Slack, which is what we mainly use for communication between fellow organizers and Maptime leadership (also known as MaptimeHQ). Please post any other questions you might have about how to get started building MaptimeCairo in the #general channel on Slack.  I'm `@brandon` there.

Thanks!
