### ISSUE TITLE
New Chapter for New Jersey, USA

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#142]
**Summary**
Maptime name: **MaptimeNJ**
Contact name: John Reiser
Date submitted: 2015-09-30 15:45:54
- [ ] Add GH admins to new team: johnjreiser
- [ ] Add Location (New Jersey, USA) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by geobrando** [comment]
Hey @johnjreiser..  Glad to see some representation in Jersey.  Could you rename to reflect the specific city or metro area in which you're planning to hold events?

**Comment by johnjreiser** [comment]
I'm working with a group to hold events across the state. We're likely going to start in South Jersey, but would want to have events in Trenton and Newark as well. 

Take care,
John

**Comment by almccon** [comment]
@johnjreiser is it an existing NJ-wide group that you're piggybacking on? If not, it seems like a Maptime in South Jersey would have more in common with MaptimePHL, and a Maptime in Newark would have more in common with MaptimeNYC than they have in common with each other.

But take my comment with a grain of salt, since I'm not local.

**Comment by johnjreiser** [comment]
New Jersey is somewhat parochial and the Delaware and Hudson seem much wider when you're in the Garden State. This group would be to encourage communication about mapping within Jersey's borders, partnering with and encouraging attendance at MaptimePHL and NYC whenever possible. There are several Jersey-specific data sets that people would want to know more about and work with in a greater capacity through community efforts, but wouldn't be "right" for PHL or NYC because the data doesn't extend into the cities.

**Comment by almccon** [comment]
Cool. Sounds good to me!

**Comment by geobrando** [comment]
Understand. We'll get you set up @johnjreiser but might want to revisit this statewide chapter should there be future interest in holding regular meetups from others in specific areas of NJ.

Once you start holding events, you could actually encourage your attendees to step up and organize a local chapter.  Most of our chapters hold monthly events but we recognize there's not always enough organizer and/or attendee interest to support this level of activity.

Welcome!

**Comment by johnjreiser** [comment]
@geobrando encouraging city or county level Maptime chapters is definitely part of the plan. I'm also working on getting a group together to help plan and coordinate events. Thanks again for setting me up and allowing me to play a part in a great movement!

**Comment by geobrando** [comment]
Hey @johnjreiser.  Do you have any interest in using our starter template to host a Jekyll webpage for MaptimeNJ?  If so, I'll clone the code into a repo for you.  It's pretty straightforward to customize and add posts/events.  If you'd like to roll with a custom webpage you can do so in the `gh-pages` branch after I create the repo for you.

https://github.com/maptime/starter
http://maptime.io/starter/

**Comment by geografa** [comment]
@johnjreiser anything we can help with here?

**Comment by geobrando** [comment]
Hi @johnjreiser. Feel free to open another ticket at any time if you wish to continue.
