### ISSUE TITLE
New Chapter for Blacksburg, VA (Virginia Tech)

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#208]
**Summary**
Maptime name: **MaptimeVT**
Contact name: Beth Bodner
Date submitted: 2016-10-12 21:34:53
- [ ] Add GH admins to new team: 
- [ ] Add Location (Blacksburg, VA (Virginia Tech)) to chapters.json and /chapters page.

**Additional tasks**
- [x] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by almccon** [comment]
There's no contact info for Beth Bodner, so I don't think we can create this yet. In any case, I'd recommend a different name, since **MaptimeVT** sounds like it means Maptime Vermont to most people (I'd guess) instead of Maptime Virginia Tech. Maybe **MaptimeBlacksburg** instead? That would also help make sure that non-students in the community don't feel excluded.

**Comment by geobrando** [comment]
Sent email to organizer asking for a github account

**Comment by bbodner** [comment]
Hi! Yes I am open to changing the name to MaptimeBlacksburg. Also I do need to set up a github account. I have never made one before and will be working on getting it done today!

**Comment by geobrando** [comment]
Hey @bbodner So you have a github account which was the first step.  I couldn't find anything online suggesting you ended up starting a chapter. As this is now over 5 years old I'm closing this. Feel free to reach out if anything is still needed.
