### ISSUE TITLE
New Chapter for Costa Rica

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#224]
__Summary__
Maptime name: __Maperespeis__
Contact name: Leo Arias
Date submitted: 2017-06-04 18:19:53

- [ ] Add GH admins to new team: elopio
- [ ] Add Location (Costa Rica) to chapters.json and /chapters page.

__Additional tasks__
- [ ] Add to Slack
- [ ] set _config.yml file

/cc @maptime/admin-onboarders

**Comment by come-maiz** [comment]
Hello, Leo Arias here. I'm wondering if there's anything missing in our request.

**Comment by jenningsanderson** [comment]
:wave: Hi @elopio, can you confirm the specific city? The chapter websites are typically organized by maptime.io/<city-name>.  Or are you hoping for maptime.io/maperespeis, instead? Thanks!

**Comment by come-maiz** [comment]
@jenningsanderson Hello!

Costa Rica is pretty small, so we have people from all provinces working in the same group, and we have been rotating the location of the meetings. I don't think we should have a chapter per city, but only one for the country.
And we named the group like a year ago, before noticing that we should have started it as a maptime chapter instead. It would be awesome if we can keep the maperespeis name. Otherwise, Maptime Costa Rica would work too.

pura vida

**Comment by geobrando** [comment]
@elopio I know this is nearly 5 years later but let me know if there anything we can do. Otherwise I'll go ahead close this ticket.

**Comment by come-maiz** [comment]
Hey. We are a little dormant at the time, which I think is appropriate. When the time comes, we'll figure out how to reactivate.
