### ISSUE TITLE
Reviving maptime

### ISSUE THREAD

**Issue by aawiseman** [maptime/maptime-admin#266]
We should figure out what the various logins are for the Maptime accounts and then figure out who should have them. First, let's see which ones we know and don't know. 

Check the box if you actually know them.

- [x] Maptime email (hello@maptime.io)
- [x] Maptime twitter (@MaptimeHQ) 

Others? Leave them below in the comments.

NOTE: Don't actually write the passwords! Just if somebody knows what they are.

**Comment by almccon** [comment]
I still have @MaptimeHQ active in my TweetDeck and I probably have the password or could reset it...

**Comment by geobrando** [comment]
I am still forwarded the hello@maptime email but have not seen any email being sent from it. I'm not even sure who owns the domain. 

@aawiseman Thanks for stepping up to help out.  As I mentioned on Slack there are some other tasks and you likely won't be able to do it all by yourself.  If no one is interested in keeping this things going someone may want to take down the website and make it clear that no one is keeping track of local chapter info here on Github. Local chapters seem to be continuing which is great!  I don't have the capacity to help out consistently.  Looks like the form @geografa created [here](http://maptime.io/start/) no longer works which is probably a good thing anyway since no one is onboarding.

@emilyashley  @bethschechter @jenningsanderson

**Comment by almccon** [comment]
Okay, I figured out how to log into gandi.net which is still on @bethschechter's account (and renewed until March 2023) and that's _also_ where the `hello@maptime.io` email is managed. There is no email account there, it's just a forwarding alias. I updated it so the people getting those emails are now @geobrando, @aawiseman, @cityhubla (Omar Ureta), and myself. I removed @emilyashley and @rsteve388, but let me know if you'd like to be added back. Also @jenningsanderson let me know if you want to get those emails too.

There are also a bunch of email forwards in there for various other maptime chapters. 

Before the gandi.net registration renews again, we should probably set it up to connect to someone else's account other than @bethschechter. We probably _shouldn't_ set it up to send notifications to `hello@maptime.io` because then what happens if we can't log into that domain that we want to manage? :)

**Comment by jenningsanderson** [comment]
Thanks @almccon! Also, I updated the DNS info on gandi.net yesterday to point to the newer Github name servers, which has allowed us to enable HTTPS on maptime.io - this appears to be working as of this morning.

With that, it seems like the maptime.io domain is all set for now — but yes, at the end of 2022, let's migrate that somewhere else...

**Comment by geobrando** [comment]
I'm cool with staying on the email list.  I can also help out here on github.  Can either @almccon or @jenningsanderson add me as an owner? I believe I used to be one but relinquished that at some point. Maybe make @aawiseman  one as well.  There are some maintenance tasks that are needed for the chapter repos.

**Comment by geobrando** [comment]
Found the maptime onboarding SOP I wrote many years ago.  

https://gist.github.com/geobrando/271bc92f3f5c5bc686019f7d59bb8bc0

@geografa Is the form on the  maptime.io site from your typeform account? Do you know why it is broken?

**Comment by almccon** [comment]
@geobrando I added you as an owner of the github org!

**Comment by geobrando** [comment]
Was able to recover the typeform account.  I'll give you the password @aawiseman if you want it.  It looks like Typeform changed their business model and there were some elements of the form that are not part of the free service. I removed it and it sort of works now but there is now a redirect page you must click through first. You can still fill out the form but I suspect this is why I tested it did not populate a chapter request. Need to figure out why as I was never clear on how it worked. My memory was that there was a google doc so it may have involved that. I'll open a separate ticket.

![image](https://user-images.githubusercontent.com/1833870/162544721-db53b567-1e3c-41ab-ac77-328d839c9390.png)

**Comment by geobrando** [comment]
I think this ticket has served its purpose so I'm closing it. Feel free to open up new tickets with specific tasks
