### ISSUE TITLE
Remove fork dependency

### ISSUE THREAD

**Issue by geobrando** [maptime/maptime-admin#46]
One thing that might be confusing to people is that this repo still exists as a fork.  Two ways to remedy this

1) If @jacquestardie deletes his repo, the maptime repo will become the "repo of record" as it's the only fork.  It can be reforked again later if so desired.

2) Contact github support and ask them to remove this as a fork

Related to this is that the recreation of the deleted repo last year from a fork had a side effect that none of the owners or those with admin privliges are "watching" it anymore.  @lyzidiamond is the only one.  Asking that @geografa @almccon @camilleanne @bethschechter click the watch button so the important people are notified with issues are submitted.  I think there are other members of @maptime/owners that have privileges as well

**Comment by jacquestardie** [comment]
I'm cool with deleting my repo, just let me know!

**Comment by almccon** [comment]
Good observation about the lack of "watching", @geobrando. I'm going to go through and make sure I'm watching all the important repos. Would be especially helpful when @geografa and the rest of the informal github admin team does the same, since I've been trying to let others take the lead on that.

Regarding deleting @jacquestardie's repo, it sounds like that would be a great solution, but I'm no expert here. Let's just do it unless anyone can point out any unintended side-effects we haven't mentioned here.

**Comment by jacquestardie** [comment]
Alright, I'm going to go ahead and delete my repo.

**Comment by geografa** [comment]
thanks for taking one for the team @jacquestardie ;)

**Comment by jacquestardie** [comment]
Anytime!
