### ISSUE TITLE
get typeform account for group

### ISSUE THREAD

**Issue by geografa** [maptime/maptime-admin#79]
right now, it's in my name. let's push to a more group-centric account

**Comment by geobrando** [comment]
@geografa Agreed.  If you use your typeform for other things then we definitely should use another account.  Looks like they're rolling out a "Team plan" but that's likely considerable :moneybag: :moneybag: and probably overkill.

Two options:

1) Set up another typeform account with a `onboarders@maptime.io` email address so all onboarders get the raw form data

2) Someone can set up an account with their personal email and then hook up a Zapier to populate a google sheet.  I think I threw this idea out there before.  Not really much use for a record of this data once they're all set up, but I know @bethschechter was using a google sheet for the master list so this could potentially be used to populate that.

**Comment by geografa** [comment]
there is a zap to dump this into a google spreadsheet but then we're at square one again with the whole email-privacy thing. Still investigating...

**Comment by geobrando** [comment]
Google sheets can be made private.  I assume you can can zap to a private sheet. I don't see any reason why [this](https://docs.google.com/spreadsheets/d/1JJMqy91xg576U642MGHmgm2W687ZSv0BJXvtso7gi4M/edit#gid=0) sheet that @bethschechter maintains has to be a public document. Probably shouldn't be anyway since it has info like mailing addresses in it.

**Comment by geobrando** [comment]
@geografa:

Beth made the sheet private.  When you create a the zap can you fit the new form data into an existing schema or does is just dump whatever fields you specify into adjacent columns?  If it's the latter we might have to re-work the master spreadsheet for this to work.  Also, it will have to be able to work with private Google sheets.

If you're fine with using your typeform account there's no reason we need another account, since no one will really have to log in except to update the form. You'll be the "formkeeper".

**Comment by geografa** [comment]
> can you fit the new form data into an existing schema or does is just dump whatever fields you specify into adjacent columns

working on this now. You may notice some tests in a secondary sheet.

**Comment by geobrando** [comment]
Great.  I need access to this data if I'm to fully onboard any new chapters.
