### ISSUE TITLE
Update chapters spreadsheet

### ISSUE THREAD

**Issue by geobrando** [maptime/maptime-admin#92]
Much of it is out of date.

To start, need to add new onboarded chapters submitted through the form before the zap was set up.

- [ ] Buffalo
- [ ] New Orleans
- [ ] Ahmedabad

**Comment by geografa** [comment]
good call. we're at 95 records. I know there are a lot of inquiries but it will be pretty awesome when we hit :100: /cc @bethschechter

**Comment by geobrando** [comment]
Seriously. it's jacked up, folks. Needs updating but just as important there should be some talk about what is and what is not worth tracking as well as if a google sheet is the most efficient way to record and store this data.  Need to reconcile how we store this data with any format and schema planned for handling monthly metrics as discussed in #62

**Comment by bethschechter** [comment]
you are totally right @geobrando. The idea behind the form sign up is to help with this. At this point, it's worth it for someone to go through the chapters and to merge the results with whatever has come in through the chapter form. 

In terms of where it goes from there, I'd like to get input from @lyzidiamond and @almccon, who first started tracking. Alan and Lyzi what are your thoughts here?

Another question: @geografa when chapters sign on, where does that information go? Does what I'm suggesting make sense given that structure?

**Comment by almccon** [comment]
Well, one thing that was useful about having it in a Google spreadsheet in the early days was that we could track protochapters and pseudochapters: people who said they _might_ be interested in starting a Maptime. Then we could play matchmaker with them and other people from their city to form a critical mass. Probably those notes should be separated from the master list of "real" chapters, and some other spreadsheet could take on the role of tracking protochapters.

**Comment by bethschechter** [comment]
Something like that sounds right to me.

**Comment by lyzidiamond** [comment]
First: let's stay positive! We did things a certain way before we got huge, now we're changing things as we get bigger. This is a process, so let's make sure to look at it that way. There's a lot that needs to be done, but it will get done! Empathy hats.

In terms of the spreadsheet, @almccon is right: I made the spreadsheet before we had processes in place for _anything_ because we needed some way for the four of us to keep track of chapters. Now that we have a form and people are coming in to start chapters that way, we don't need the spreadsheet to keep track of our chapters anymore.

This does relate to something else I'm planning on tackling this week -- keeping track of chapters once they've said they want to start and making sure we don't have chapters on our official list that are inactive. It seems like there are three possible categories of chapters: inactive, active, and preliminary/interested. When we have actions we want to take with respect to each of these types of chapters, we can adapt the system around them. Look for a ticket about that this week and we can continue the conversation from there.

**Comment by geografa** [comment]
@bethschechter to answer your question, new chapter signups from the form on the site go straight to Typeform (my account) where it's recorded with some extra fields. I then use a Zap to push it to a GH issue for a repo request and to the Google spreadsheet for tracking. The spreadhseet holds a lot of info which isn't being populated b/c that's more on the admin side of management. The issue I see here is that no one  has time to keep this up.

**Comment by geobrando** [comment]
Thanks for tackling this @lyzidiamond.  I'm going to chip away at updating the important information in the current form and we'll continue this in the new issue.
